### ISSUE TITLE
Crash by air

### ISSUE THREAD

**Issue by powncc** [zmaster587/libVulpes#18]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  TweaksLoadingPlugin (CCTweaks-1.11.2-1.5.0-pr2.jar)
  CCLCorePlugin (CodeChickenLib-1.11.2-3.0.0.307-universal.jar)
  CoreModLoader (applied-llamagistics-1.11.2-rv5-beta-7.jar)
  NEICorePlugin (NotEnoughItems-1.11.2-2.3.0.227-universal.jar)
  SpongeCoremod (spongeforge-1.11.2-2476-6.1.0-BETA-2636.jar)
  CoFH Loading Plugin (CoFHCore-1.11.2-4.2.8.16-universal.jar)
  AdvancedRocketryPlugin (AdvancedRocketry-1.11.2-1.2.4.jar)
  TransformerLoader (OpenComputers-MC1.11.2-1.7.0.40.jar)
  IC2core (industrialcraft-2-2.7.81-ex111.jar)
Contact their authors BEFORE contacting forge

// I blame Dinnerbone.

Time: 10/15/17 7:07 PM
Description: Ticking block entity

java.lang.IllegalArgumentException: Cannot get property PropertyBool{name=state, clazz=class java.lang.Boolean, values=[true, false]} as it does not exist in BlockStateContainer{block=minecraft:air, properties=[]}
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:201)
	at zmaster587.libVulpes.tile.TileInventoriedForgePowerMachine.setState(TileInventoriedForgePowerMachine.java:31)
	at zmaster587.libVulpes.tile.TileInventoriedForgePowerMachine.notEnoughBufferForFunction(TileInventoriedForgePowerMachine.java:63)
	at zmaster587.libVulpes.tile.TileInventoriedForgePowerMachine.func_73660_a(TileInventoriedForgePowerMachine.java:56)
	at zmaster587.libVulpes.tile.energy.TileCoalGenerator.func_73660_a(TileCoalGenerator.java:65)
	at net.minecraft.world.World.redirect$onUpdateTileEntities$zkf000(World.java:5599)
	at net.minecraft.world.World.func_72939_s(World.java:6020)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1784)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1056)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:372)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:201)
	at zmaster587.libVulpes.tile.TileInventoriedForgePowerMachine.setState(TileInventoriedForgePowerMachine.java:31)
	at zmaster587.libVulpes.tile.TileInventoriedForgePowerMachine.notEnoughBufferForFunction(TileInventoriedForgePowerMachine.java:63)
	at zmaster587.libVulpes.tile.TileInventoriedForgePowerMachine.func_73660_a(TileInventoriedForgePowerMachine.java:56)
	at zmaster587.libVulpes.tile.energy.TileCoalGenerator.func_73660_a(TileCoalGenerator.java:65)
	at net.minecraft.world.World.redirect$onUpdateTileEntities$zkf000(World.java:5599)

-- Block entity being ticked --
Details:
	Name: minecraft:vulpescoalgenerator // zmaster587.libVulpes.tile.energy.TileCoalGenerator
	Block type: ID #0 (tile.air // net.minecraft.block.BlockAir)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (-518,47,-44), Chunk: (at 10,2,4 in -33,-3; contains blocks -528,0,-48 to -513,255,-33), Region: (-2,-1; contains chunks -64,-32 to -33,-1, blocks -1024,0,-512 to -513,255,-1)
	Actual block type: ID #0 (tile.air // net.minecraft.block.BlockAir)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:6020)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['PwnCC'/274534, l='MpServer', x=-696.13, y=81.65, z=97.32]]
	Chunk stats: MultiplayerChunkCache: 420, 420
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-434,65,70), Chunk: (at 14,4,6 in -28,4; contains blocks -448,0,64 to -433,255,79), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 98694994 game time, 7575 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 72 total; [EntityPlayerSP['PwnCC'/274534, l='MpServer', x=-696.13, y=81.65, z=97.32], EntityChicken['Chicken'/293901, l='MpServer', x=-632.83, y=64.00, z=160.35], EntityChicken['Chicken'/293902, l='MpServer', x=-635.55, y=62.66, z=139.61], EntityChicken['Chicken'/293903, l='MpServer', x=-629.36, y=62.66, z=146.61], EntityChicken['Chicken'/293898, l='MpServer', x=-639.50, y=63.00, z=161.50], EntityChicken['Chicken'/293899, l='MpServer', x=-639.50, y=64.00, z=162.50], EntityOtherPlayerMP['powerboat9'/229889, l='MpServer', x=-505.26, y=59.70, z=-16.03], EntityChicken['Chicken'/292884, l='MpServer', x=-608.56, y=68.00, z=92.91], EntityChicken['Chicken'/292886, l='MpServer', x=-614.87, y=63.00, z=33.92], EntityChicken['Chicken'/293911, l='MpServer', x=-632.12, y=64.00, z=45.33], EntityChicken['Chicken'/292880, l='MpServer', x=-617.39, y=64.00, z=141.81], EntityItem['item.item.egg'/293904, l='MpServer', x=-629.65, y=62.00, z=147.54], EntityChicken['Chicken'/293905, l='MpServer', x=-636.57, y=64.00, z=159.63], EntityItem['item.item.egg'/293906, l='MpServer', x=-636.09, y=64.00, z=159.81], EntityChicken['Chicken'/293912, l='MpServer', x=-628.20, y=64.00, z=97.75], EntityItem['item.item.egg'/293913, l='MpServer', x=-628.88, y=64.00, z=98.69], EntityMinecartChest['Minecart with Chest'/296996, l='MpServer', x=-671.50, y=12.06, z=57.50], EntityChicken['Chicken'/296997, l='MpServer', x=-666.20, y=70.00, z=109.32], EntityItem['item.item.porkchopRaw'/297004, l='MpServer', x=-674.58, y=45.00, z=53.45], EntityItem['item.tile.torch'/297005, l='MpServer', x=-672.38, y=21.00, z=64.88], EntityPig['Pig'/297006, l='MpServer', x=-687.50, y=67.00, z=78.50], EntityPig['Pig'/297007, l='MpServer', x=-687.50, y=67.00, z=79.50], EntityItem['item.tile.torch'/297008, l='MpServer', x=-672.13, y=14.00, z=126.17], EntityChicken['Chicken'/297029, l='MpServer', x=-702.80, y=64.00, z=37.80], EntityChicken['Chicken'/297030, l='MpServer', x=-701.50, y=64.00, z=34.50], EntityChicken['Chicken'/297031, l='MpServer', x=-702.50, y=64.00, z=34.50], EntityItem['item.tile.torch'/297036, l='MpServer', x=-690.02, y=17.00, z=71.91], EntityItem['item.tile.torch'/297037, l='MpServer', x=-694.83, y=18.00, z=84.11], EntityMinecartChest['Minecart with Chest'/297038, l='MpServer', x=-688.50, y=18.06, z=92.50], EntityItem['item.tile.torch'/297039, l='MpServer', x=-706.98, y=17.00, z=58.07], EntityChicken['Chicken'/297032, l='MpServer', x=-702.50, y=64.00, z=34.50], EntityMinecartChest['Minecart with Chest'/297033, l='MpServer', x=-695.50, y=17.06, z=49.50], EntityMinecartChest['Minecart with Chest'/297034, l='MpServer', x=-694.50, y=21.06, z=69.50], EntityItem['item.tile.torch'/297035, l='MpServer', x=-690.45, y=21.00, z=76.91], EntityChicken['Chicken'/297044, l='MpServer', x=-715.83, y=68.00, z=86.30], EntityItem['item.tile.rail'/297046, l='MpServer', x=-735.22, y=18.00, z=57.13], EntityChicken['Chicken'/297047, l='MpServer', x=-721.50, y=68.00, z=79.50], EntityItem['item.tile.torch'/297040, l='MpServer', x=-718.30, y=17.00, z=59.80], EntityItem['item.tile.rail'/297041, l='MpServer', x=-719.77, y=17.00, z=58.33], EntityMinecartChest['Minecart with Chest'/297043, l='MpServer', x=-705.50, y=18.06, z=17.50], EntityChicken['Chicken'/297052, l='MpServer', x=-726.50, y=69.00, z=92.50], EntityChicken['Chicken'/297053, l='MpServer', x=-723.50, y=68.00, z=91.50], EntityChicken['Chicken'/297054, l='MpServer', x=-721.50, y=67.00, z=105.50], EntityChicken['Chicken'/297055, l='MpServer', x=-722.76, y=66.00, z=111.21], EntityChicken['Chicken'/297048, l='MpServer', x=-721.50, y=68.00, z=80.50], EntityChicken['Chicken'/297049, l='MpServer', x=-721.50, y=68.00, z=81.50], EntityChicken['Chicken'/297050, l='MpServer', x=-727.50, y=69.00, z=95.50], EntityChicken['Chicken'/297051, l='MpServer', x=-727.50, y=69.00, z=94.50], EntityChicken['Chicken'/297060, l='MpServer', x=-729.50, y=65.00, z=167.50], EntityChicken['Chicken'/297056, l='MpServer', x=-720.50, y=66.00, z=107.50], EntityChicken['Chicken'/297057, l='MpServer', x=-722.43, y=66.00, z=112.88], EntityChicken['Chicken'/297058, l='MpServer', x=-734.50, y=66.00, z=161.50], EntityChicken['Chicken'/297059, l='MpServer', x=-730.50, y=65.00, z=163.50], EntityChicken['Chicken'/297068, l='MpServer', x=-749.50, y=69.00, z=109.50], EntityChicken['Chicken'/297069, l='MpServer', x=-736.50, y=66.00, z=164.50], EntityChicken['Chicken'/297070, l='MpServer', x=-744.50, y=67.00, z=126.50], EntityChicken['Chicken'/297071, l='MpServer', x=-745.50, y=67.00, z=125.50], EntityChicken['Chicken'/297065, l='MpServer', x=-749.50, y=69.00, z=108.50], EntityChicken['Chicken'/297066, l='MpServer', x=-749.50, y=69.00, z=108.50], EntityChicken['Chicken'/297067, l='MpServer', x=-749.50, y=68.00, z=107.50], EntityChicken['Chicken'/297078, l='MpServer', x=-763.50, y=71.00, z=146.50], EntityChicken['Chicken'/297079, l='MpServer', x=-765.54, y=72.00, z=148.76], EntityChicken['Chicken'/297072, l='MpServer', x=-745.50, y=67.00, z=128.50], EntityChicken['Chicken'/297073, l='MpServer', x=-746.50, y=67.00, z=128.50], EntityChicken['Chicken'/297080, l='MpServer', x=-765.50, y=72.00, z=147.50], EntityChicken['Chicken'/297081, l='MpServer', x=-762.50, y=71.00, z=144.50], EntityOtherPlayerMP['powerboat9'/229889, l='MpServer', x=-518.26, y=47.00, z=-47.65], EntityChicken['Chicken'/229108, l='MpServer', x=-605.58, y=63.00, z=107.87], EntityOtherPlayerMP['powerboat9'/281795, l='MpServer', x=-519.50, y=47.10, z=-48.50], EntityOtherPlayerMP['FlamerGamer1234'/279299, l='MpServer', x=-468.27, y=67.00, z=128.89], EntityOtherPlayerMP['powerboat9'/281795, l='MpServer', x=-556.06, y=15.05, z=-60.29], EntityOtherPlayerMP['FlamerGamer1234'/282329, l='MpServer', x=-477.36, y=64.00, z=48.53]]
	Retry entities: 0 total; []
	Server brand: fml,forge,sponge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:415)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2655)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:393)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 713006208 bytes (679 MB) / 3175612416 bytes (3028 MB) up to 3175612416 bytes (3028 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3G -Xms3G
	IntCache: cache: 0, tcache: 0, allocated: 15, tallocated: 95
	FML: MCP 9.38 Powered by Forge 13.20.1.2476 59 mods loaded, 59 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	minecraft{1.11.2} [Minecraft] (minecraft.jar) 
	UCHIJA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.1.2476.jar) 
	UCHIJA	forge{13.20.1.2476} [Minecraft Forge] (forge-1.11.2-13.20.1.2476.jar) 
	UCHIJA	advancedrocketrycore{1} [Advanced Rocketry Core] (minecraft.jar) 
	UCHIJA	appliedenergistics2-core{rv5-beta-7} [Applied Llamagistics Core] (minecraft.jar) 
	UCHIJA	opencomputers|core{1.7.0.40} [OpenComputers (Core)] (minecraft.jar) 
	UCHIJA	spongeapi{6.1.0-SNAPSHOT-c4a7afd} [SpongeAPI] (spongeforge-1.11.2-2476-6.1.0-BETA-2636.jar) 
	UCHIJA	sponge{1.11.2-2476-6.1.0-BETA-2636} [SpongeForge] (spongeforge-1.11.2-2476-6.1.0-BETA-2636.jar) 
	UCHIJA	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHIJA	<CCTweaks ASM>{1.5.0-pr2} [<CCTweaks ASM>] (minecraft.jar) 
	UCHIJA	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.11.2.jar) 
	UCHIJA	libvulpes{0.2.6.} [Vulpes library] (LibVulpes-1.11.2-0.2.6-universal.jar) 
	UCHIJA	advancedrocketry{1.2.4} [Advanced Rocketry] (AdvancedRocketry-1.11.2-1.2.4.jar) 
	UCHIJA	ageofweapons{0.10.0} [Age of Weapons] (Age of Weapons 1.11.2  (v.0.10.0).jar) 
	UCHIJA	ic2{2.7.81-ex111} [IndustrialCraft 2] (industrialcraft-2-2.7.81-ex111.jar) 
	UCHIJA	cofhcore{4.2.8} [CoFH Core] (CoFHCore-1.11.2-4.2.8.16-universal.jar) 
	UCHIJA	computercraft{1.80pr1} [ComputerCraft] (ComputerCraft-SquidDev-CC-ComputerCraft-feature-minecraft-1.11.2-1.80pr1-build0.jar) 
	UCHIJA	jei{4.5.1.296} [Just Enough Items] (jei_1.11.2-4.5.1.296.jar) 
	UCHIJA	mekanism{9.3.5} [Mekanism] (Mekanism-1.11.2-9.3.5.206.jar) 
	UCHIJA	opencomputers{1.7.0.40} [OpenComputers] (OpenComputers-MC1.11.2-1.7.0.40.jar) 
	UCHIJA	codechickenlib{3.0.0.307} [CodeChicken Lib] (CodeChickenLib-1.11.2-3.0.0.307-universal.jar) 
	UCHIJA	thermalfoundation{2.2.5} [Thermal Foundation] (ThermalFoundation-1.11.2-2.2.5.16-universal.jar) 
	UCHIJA	thermalexpansion{5.2.7} [Thermal Expansion] (ThermalExpansion-1.11.2-5.2.7.24-universal.jar) 
	UCHIJA	appliedenergistics2{rv5-beta-7} [Applied Llamagistics] (applied-llamagistics-1.11.2-rv5-beta-7.jar) 
	UCHIJA	buildcraftlib{7.99.7} [BuildCraft Lib] (buildcraft-7.99.7.jar) 
	UCHIJA	buildcraftcore{7.99.7} [BuildCraft] (buildcraft-7.99.7.jar) 
	UCHIJA	buildcraftbuilders{7.99.7} [BC Builders] (buildcraft-7.99.7.jar) 
	UCHIJA	buildcraftenergy{7.99.7} [BC Energy] (buildcraft-7.99.7.jar) 
	UCHIJA	buildcraftfactory{7.99.7} [BC Factory] (buildcraft-7.99.7.jar) 
	UCHIJA	buildcraftrobotics{7.99.7} [BC Robotics] (buildcraft-7.99.7.jar) 
	UCHIJA	buildcraftsilicon{7.99.7} [BC Silicon] (buildcraft-7.99.7.jar) 
	UCHIJA	buildcrafttransport{7.99.7} [BC Transport] (buildcraft-7.99.7.jar) 
	UCHIJA	cctweaks{1.5.0-pr2} [CCTweaks] (CCTweaks-1.11.2-1.5.0-pr2.jar) 
	UCHIJA	chickenchunks{2.3.1.68} [ChickenChunks] (ChickenChunks-1.11.2-2.3.1.68-universal.jar) 
	UCHIJA	extendedrenderer{v1.0} [Extended Renderer] (CoroUtil-1.11.2.jar) 
	UCHIJA	coroutil{1.11.2-1.1.19} [CoroUtil Library] (CoroUtil-1.11.2.jar) 
	UCHIJA	configmod{v1.0} [Extended Mod Config] (CoroUtil-1.11.2.jar) 
	UCHIJA	modcurrency{1.11.2-1.2.0} [Good Ol' Currency Mod] (Currency-1.11.2-1.2.0.jar) 
	UCHIJA	cyberware{alpha-0.2.10} [Cyberware] (cyberware-1.11.2-alpha-0.2.10.jar) 
	UCHIJA	zerocore{1.11.2-0.1.0.6} [Zero CORE] (zerocore-1.11.2-0.1.0.6.jar) 
	UCHIJA	bigreactors{1.11.2-0.4.5.30} [Extreme Reactors] (ExtremeReactors-1.11.2-0.4.5.30.jar) 
	UCHIJA	geneticsreborn{1.07} [Genetics Reborn] (geneticsreborn-mc1.11.2-v1.08.jar) 
	UCHIJA	grapplemod{1.11.2-v10} [Grappling hook mod] (grapplemod-1.11.2-v10.jar) 
	UCHIJA	griefprevention{4.1.0} [GriefPrevention] (griefprevention-1.11.2-4.1.0.413.jar) 
	UCHIJA	immersiveengineering{0.11-63} [Immersive Engineering] (ImmersiveEngineering-0.11-63.jar) 
	UCHIJA	industrialwires{1.5-19} [Industrial Wires] (IndustrialWires-1.5-19.jar) 
	UCHIJA	luckperms{3.4.7} [LuckPerms] (LuckPerms-Sponge-3.4.7.jar) 
	UCHIJA	mekanismgenerators{9.3.5} [MekanismGenerators] (MekanismGenerators-1.11.2-9.3.5.206.jar) 
	UCHIJA	mekanismtools{9.3.5} [MekanismTools] (MekanismTools-1.11.2-9.3.5.206.jar) 
	UCHIJA	mw{1.9} [Modern Warfare] (mw-1.9_mc1.11.2.jar) 
	UCHIJA	nei{${mod_version}} [Not Enough Items] (NotEnoughItems-1.11.2-2.3.0.227-universal.jar) 
	UCHIJA	nucleus{1.1.3-LTS-S6.0} [Nucleus] (Nucleus-1.1.3-LTS-S6.0-MC1.11.2-plugin.jar) 
	UCHIJA	plethora-core{1.1.7-pr0} [Plethora Core] (plethora-1.11.2-1.1.7-pr0.jar) 
	UCHIJA	plethora{1.1.7-pr0} [Plethora] (plethora-1.11.2-1.1.7-pr0.jar) 
	UCHIJA	reforged{0.7.4} [Reforged] (Reforged-0.7.4-1.11+.jar) 
	UCHIJA	thermaldynamics{2.2.7} [Thermal Dynamics] (ThermalDynamics-1.11.2-2.2.7.14-universal.jar) 
	UCHIJA	weather2{1.11.2-2.5} [Localized Weather & Storms] (Weather-Tornadoes-1.11.2.jar) 
	UCHIJA	worldedit{6.1.6} [WorldEdit] (worldedit-forge-mc1.11-6.1.6-dist.jar) 
	Loaded coremods (and transformers): 
TweaksLoadingPlugin (CCTweaks-1.11.2-1.5.0-pr2.jar)
  org.squiddev.cctweaks.core.asm.ASMTransformer
CCLCorePlugin (CodeChickenLib-1.11.2-3.0.0.307-universal.jar)
  codechicken.lib.asm.ClassHierarchyManager
  codechicken.lib.asm.CCL_ASMTransformer
CoreModLoader (applied-llamagistics-1.11.2-rv5-beta-7.jar)
  appeng.coremod.transformer.ASMIntegration
NEICorePlugin (NotEnoughItems-1.11.2-2.3.0.227-universal.jar)
  codechicken.nei.asm.NEITransformer
SpongeCoremod (spongeforge-1.11.2-2476-6.1.0-BETA-2636.jar)
  org.spongepowered.common.launch.transformer.SpongeSuperclassTransformer
CoFH Loading Plugin (CoFHCore-1.11.2-4.2.8.16-universal.jar)
  cofh.asm.CoFHClassTransformer
  cofh.asm.repack.codechicken.lib.asm.ClassHierarchyManager
AdvancedRocketryPlugin (AdvancedRocketry-1.11.2-1.2.4.jar)
  zmaster587.advancedRocketry.asm.ClassTransformer
TransformerLoader (OpenComputers-MC1.11.2-1.7.0.40.jar)
  li.cil.oc.common.asm.ClassTransformer
IC2core (industrialcraft-2-2.7.81-ex111.jar)
  
	GL info: ' Vendor: 'Intel' Version: '4.4.0 - Build 21.20.16.4550' Renderer: 'Intel(R) HD Graphics 520'
	CCTweaks version issue: CCTweaks 1.5.0-pr2 was tested against ComputerCraft 1.80pr0 but is running against 1.80pr1.
	Some CCTweaks/ComputerCraft features may not work correctly - please check CCTweaks for updates.
	If you encounter issues then try to reproduce without CCTweaks installed, then report to the appropriate mod author.
	AE2 Version: beta rv5-beta-7 for Forge 13.20.1.2388
	codechickenlib Invalid Fingerprint Reports: - No invalid fingerprints.: 
	chickenchunks Invalid Fingerprint Reports: - No invalid fingerprints.: 
	nei Invalid Fingerprint Reports: - No invalid fingerprints.: 
	AE2 Integration: IC2:ON, BUILDCRAFT:OFF, COFH_HAMMER:ON, RF:ON, RFItem:ON, Waila:OFF, JEI:ON, OpenComputers:ON, THE_ONE_PROBE:OFF, MEKANISM:ON, CHISEL:OFF
	Launched Version: 1.11.2-forge1.11.2-13.20.1.2476
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics 520 GL version 4.4.0 - Build 21.20.16.4550, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge,sponge'
	Type: Client (map_client.txt)
	Resource Packs: John Smith Legacy 1.7.10 v1.2.24 (1).zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz

**Comment by zmaster587** [comment]
Added block check
