### ISSUE TITLE
[1.12.2] Jetpack toggle key doesn't work on dedicated servers

### ISSUE THREAD

**Issue by Thutmose** [zmaster587/libVulpes#26]
This method here: https://github.com/zmaster587/libVulpes/blob/1.12/src/main/java/zmaster587/libVulpes/util/InputSyncHandler.java#L31 is SideOnly CLIENT, so it doesn't work on dedicated servers, the list being obtained from however is public, so it can be replaced with stack = player.inventory.armorInventory.get(2);

Here is the snippet of log that is relevant:
```
12.11 18:47:00 [Server] INFO java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: net.minecraft.entity.player.InventoryPlayer.func_70440_f(I)Lnet/minecraft/item/ItemStack;
12.11 18:47:00 [Server] INFO at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_144]
12.11 18:47:00 [Server] INFO at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_144]
12.11 18:47:00 [Server] INFO at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
12.11 18:47:00 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:721) [MinecraftServer.class:?]
12.11 18:47:00 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
12.11 18:47:00 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
12.11 18:47:00 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
12.11 18:47:00 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
12.11 18:47:00 [Server] INFO Caused by: java.lang.NoSuchMethodError: net.minecraft.entity.player.InventoryPlayer.func_70440_f(I)Lnet/minecraft/item/ItemStack;
12.11 18:47:00 [Server] INFO at zmaster587.libVulpes.util.InputSyncHandler.updateKeyPress(InputSyncHandler.java:31) ~[InputSyncHandler.class:?]
12.11 18:47:00 [Server] INFO at zmaster587.libVulpes.network.PacketChangeKeyState.executeServer(PacketChangeKeyState.java:45) ~[PacketChangeKeyState.class:?]
12.11 18:47:00 [Server] INFO at zmaster587.libVulpes.network.BasePacket$BasePacketHandlerServer$executor.run(BasePacket.java:120) ~[BasePacket$BasePacketHandlerServer$executor.class:?]
```

**Comment by nicohdemus** [comment]
same issue in 1.11.2

see issue in Adv. Rocketry section for more details...

https://github.com/zmaster587/AdvancedRocketry/issues/776

**Comment by nicohdemus** [comment]
This is really bad on dedicated servers. The jetpack is not usable and it's extremely difficult to work on a space station / starship without one.
