### ISSUE TITLE
Holo Projector doesn't show modded blocks

### ISSUE THREAD

**Issue by FangedHex** [zmaster587/libVulpes#8]
Sorry if the title didn't explain the problem itself but I'm happy that you moved to 1.11.2 so I tested your mod and I tried the holo projector to build some stuff, it doesn't crash the game but I got : 
`[15:04:53] [Client thread/ERROR] [FML]: Unable to access any field [field_145855_i, REGISTRY] on type net.minecraft.tileentity.TileEntity
net.minecraftforge.fml.relauncher.ReflectionHelper$UnableToAccessFieldException: net.minecraftforge.fml.relauncher.ReflectionHelper$UnableToFindFieldException: java.lang.NoSuchFieldException: REGISTRY
	at net.minecraftforge.fml.relauncher.ReflectionHelper.getPrivateValue(ReflectionHelper.java:134) ~[forge-1.11.2-13.20.0.2304.jar:?]
	at net.minecraftforge.fml.common.ObfuscationReflectionHelper.getPrivateValue(ObfuscationReflectionHelper.java:67) [ObfuscationReflectionHelper.class:?]
	at zmaster587.libVulpes.util.ZUtils.createTile(ZUtils.java:98) [ZUtils.class:unspecified]
	at zmaster587.libVulpes.tile.multiblock.TilePlaceholder.func_145839_a(TilePlaceholder.java:95) [TilePlaceholder.class:unspecified]
	at zmaster587.libVulpes.tile.TileSchematic.func_145839_a(TileSchematic.java:84) [TileSchematic.class:unspecified]
	at zmaster587.libVulpes.tile.multiblock.TilePlaceholder.onDataPacket(TilePlaceholder.java:66) [TilePlaceholder.class:unspecified]
	at net.minecraft.client.network.NetHandlerPlayClient.func_147273_a(NetHandlerPlayClient.java:1223) [bno.class:?]
	at net.minecraft.network.play.server.SPacketUpdateTileEntity.func_148833_a(SourceFile:53) [fz.class:?]
	at net.minecraft.network.play.server.SPacketUpdateTileEntity.func_148833_a(SourceFile:11) [fz.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [fo$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_131]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_131]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1046) [bes.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:372) [bes.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: net.minecraftforge.fml.relauncher.ReflectionHelper$UnableToFindFieldException: java.lang.NoSuchFieldException: REGISTRY
	at net.minecraftforge.fml.relauncher.ReflectionHelper.findField(ReflectionHelper.java:107) ~[forge-1.11.2-13.20.0.2304.jar:?]
	at net.minecraftforge.fml.relauncher.ReflectionHelper.getPrivateValue(ReflectionHelper.java:130) ~[forge-1.11.2-13.20.0.2304.jar:?]
	... 21 more
Caused by: java.lang.NoSuchFieldException: REGISTRY
	at java.lang.Class.getDeclaredField(Class.java:2070) ~[?:1.8.0_131]
	at net.minecraftforge.fml.relauncher.ReflectionHelper.findField(ReflectionHelper.java:98) ~[forge-1.11.2-13.20.0.2304.jar:?]
	at net.minecraftforge.fml.relauncher.ReflectionHelper.getPrivateValue(ReflectionHelper.java:130) ~[forge-1.11.2-13.20.0.2304.jar:?]
	... 21 more
[15:04:53] [Client thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_131]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_131]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1046) [bes.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:372) [bes.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NullPointerException
	at zmaster587.libVulpes.util.ZUtils.createTile(ZUtils.java:109) ~[ZUtils.class:unspecified]
	at zmaster587.libVulpes.tile.multiblock.TilePlaceholder.func_145839_a(TilePlaceholder.java:95) ~[TilePlaceholder.class:unspecified]
	at zmaster587.libVulpes.tile.TileSchematic.func_145839_a(TileSchematic.java:84) ~[TileSchematic.class:unspecified]
	at zmaster587.libVulpes.tile.multiblock.TilePlaceholder.onDataPacket(TilePlaceholder.java:66) ~[TilePlaceholder.class:unspecified]
	at net.minecraft.client.network.NetHandlerPlayClient.func_147273_a(NetHandlerPlayClient.java:1223) ~[bno.class:?]
	at net.minecraft.network.play.server.SPacketUpdateTileEntity.func_148833_a(SourceFile:53) ~[fz.class:?]
	at net.minecraft.network.play.server.SPacketUpdateTileEntity.func_148833_a(SourceFile:11) ~[fz.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fo$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_131]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_131]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 9 more`
In the minecraft console. Also your modded blocks appear as missing texture block ( purple + black ) and when I look at it : it's named "Air" :/

Thank you in advance for taking your free times to fix your awesome mod :D 

PS : If you need more informations, just ask I will try my best to help ;)

**Comment by zmaster587** [comment]
Looks like I missed another obfuscation change, will have a build up later today with the fix.

**Comment by FangedHex** [comment]
You can close the other issue on your Advanced Rocketry repository :)
